;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(evil-change
                               evil-backward-WORD-begin
                               evil-normal-state
                               evil-digit-argument-or-evil-beginning-of-line
                               evil-exit-visual-state
                               evil-delete-char
                               evil-exit-emacs-state
                               evil-delete
                               evil-insert
                               evil-end-of-line
                               evil-backward-word-begin
                               keyboard-escape-quit
                               evil-search-next
                               evil-forward-word-begin
                               evil-forward-char
                               evil-backward-char))

(setq mc/cmds-to-run-once '(yas-expand
                            evil-append
                            evil-scroll-down
                            evil-next-line
                            evil-previous-line))

                            
                               